spring:
  data:
    mongodb:
      database: ${mongo.database:local}
      port: ${mongo.port:27017}
      host: ${mongo.host:localhost}
      username: ${mongo.user:user}
      password: ${mongo.password:password}

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: GET
