spring:
  application:
    name: monkey-mongo-service
    cloud:
      kubernetes:
        config:
          sources:
            # Spring Cloud Kubernetes will lookup a ConfigMap named c1 in namespace default-namespace
            - name: c1

  data:
    mongodb:
      database: ${database-name:local}
      port: ${database-port:27017}
      host: ${database-host:localhost}
      username: ${database-user:user}
      password: ${database-password:password}


management:
  info:
    git:
      mode: full
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: GET
